### PR TITLE
Support MsTest in VS2013

### PR DESCRIPTION
**Pull request by automatonic**
added string to match:
Microsoft.VisualStudio.QualityTools.UnitTestFramework

### CODE REVIEW

**Comment by automatonic** [comment]
Feels a bit arbitrary to just grab a substring out of the middle. Would it be better to try and match the full assembly name?

**Comment by automatonic** [comment]
This does, however, fix:
```csharp
[TestMethod]
        public void ShouldBeInUnitTestRunner()
        {
            ModeDetector.InUnitTestRunner().Should().BeTrue("this is a unit test");
        }
```

**Comment by automatonic** [comment]
@paulcbetts i am still getting
```
  Message=The current thread has no Dispatcher associated with it.
  Source=System.Reactive.Windows.Threading
  StackTrace:
       at System.Reactive.Concurrency.DispatcherScheduler.get_Current()
  InnerException: 
```
from a test running code with 
```
var list = new ReactiveList<Something>();
```

Would I need a new splat release to get this fixed? Or can I:

```csharp
ModeDetector.OverrideModeDetector(new TweakedPlatformModeDetector());
```
 In time for ReactiveUI to pick it up somehow?

**Comment by paulcbetts** [comment]
Looks good!

**Comment by paulcbetts** [comment]
> Would I need a new splat release to get this fixed? 

Yeah, probably - fixing this in a unit test assembly is a particular pain

**Pull request merged**
